
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SATISFIED = 58;
  public static final int AS = 64;
  public static final int IDENTIFIER = 88;
  public static final int TIMES = 61;
  public static final int NAMED = 51;
  public static final int DIVISION = 5;
  public static final int GT = 41;
  public static final int ARROW = 47;
  public static final int BASED = 29;
  public static final int CHAINSIGN = 39;
  public static final int GE = 43;
  public static final int SEMI = 16;
  public static final int UNTIL = 76;
  public static final int CAUGHT = 75;
  public static final int LIKE = 32;
  public static final int ARGS = 81;
  public static final int PROPS = 69;
  public static final int CATCH = 28;
  public static final int COMMA = 18;
  public static final int SUM = 2;
  public static final int RBRACE = 15;
  public static final int DEFINE = 50;
  public static final int RPAREN = 13;
  public static final int LT = 42;
  public static final int LBRACE = 14;
  public static final int REMEMBER = 68;
  public static final int ACTION = 71;
  public static final int LPAREN = 12;
  public static final int LOOP = 60;
  public static final int PROP = 85;
  public static final int ARE = 57;
  public static final int FALSE = 56;
  public static final int NOT = 65;
  public static final int LE = 44;
  public static final int INSTANCE = 37;
  public static final int OBJECT = 70;
  public static final int ERROR = 74;
  public static final int THEN = 59;
  public static final int PARAMS = 53;
  public static final int BEHAVIOUR = 34;
  public static final int EMPTY = 38;
  public static final int MOD = 7;
  public static final int CLASS = 33;
  public static final int MULTIPLY = 4;
  public static final int NUMBER = 89;
  public static final int TAB = 77;
  public static final int TRUE = 55;
  public static final int EXEC = 46;
  public static final int WHILE = 24;
  public static final int EQUAL = 11;
  public static final int ASSIGN = 40;
  public static final int EACH = 66;
  public static final int SWITCH = 22;
  public static final int DO = 73;
  public static final int FOR = 19;
  public static final int RETURN = 49;
  public static final int ELSE = 21;
  public static final int TRY = 27;
  public static final int POWER = 6;
  public static final int EOF = 0;
  public static final int ITEM = 80;
  public static final int CONDITIONS = 54;
  public static final int FUNCTION = 35;
  public static final int CAREFULLY = 72;
  public static final int IS = 25;
  public static final int IN = 67;
  public static final int OR = 9;
  public static final int error = 1;
  public static final int START = 78;
  public static final int BEHAVES = 31;
  public static final int ON = 30;
  public static final int IF = 20;
  public static final int OF = 36;
  public static final int END = 79;
  public static final int COLON = 17;
  public static final int BY = 62;
  public static final int SUBTRACT = 3;
  public static final int FOREACH = 26;
  public static final int RBRACKET = 83;
  public static final int ENCAPSULATE = 48;
  public static final int CASE = 23;
  public static final int NEW = 84;
  public static final int STRING = 90;
  public static final int STEP = 63;
  public static final int DOING = 87;
  public static final int AND = 8;
  public static final int VALUE = 86;
  public static final int UMINUS = 10;
  public static final int LBRACKET = 82;
  public static final int WITH = 52;
  public static final int NE = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUM",
  "SUBTRACT",
  "MULTIPLY",
  "DIVISION",
  "POWER",
  "MOD",
  "AND",
  "OR",
  "UMINUS",
  "EQUAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COLON",
  "COMMA",
  "FOR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "WHILE",
  "IS",
  "FOREACH",
  "TRY",
  "CATCH",
  "BASED",
  "ON",
  "BEHAVES",
  "LIKE",
  "CLASS",
  "BEHAVIOUR",
  "FUNCTION",
  "OF",
  "INSTANCE",
  "EMPTY",
  "CHAINSIGN",
  "ASSIGN",
  "GT",
  "LT",
  "GE",
  "LE",
  "NE",
  "EXEC",
  "ARROW",
  "ENCAPSULATE",
  "RETURN",
  "DEFINE",
  "NAMED",
  "WITH",
  "PARAMS",
  "CONDITIONS",
  "TRUE",
  "FALSE",
  "ARE",
  "SATISFIED",
  "THEN",
  "LOOP",
  "TIMES",
  "BY",
  "STEP",
  "AS",
  "NOT",
  "EACH",
  "IN",
  "REMEMBER",
  "PROPS",
  "OBJECT",
  "ACTION",
  "CAREFULLY",
  "DO",
  "ERROR",
  "CAUGHT",
  "UNTIL",
  "TAB",
  "START",
  "END",
  "ITEM",
  "ARGS",
  "LBRACKET",
  "RBRACKET",
  "NEW",
  "PROP",
  "VALUE",
  "DOING",
  "IDENTIFIER",
  "NUMBER",
  "STRING"
  };
}

