
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 33;
  public static final int POWER = 6;
  public static final int GE = 42;
  public static final int EMPTY = 37;
  public static final int UMINUS = 8;
  public static final int CASE = 21;
  public static final int SUBTRACT = 3;
  public static final int LPAREN = 10;
  public static final int SEMI = 14;
  public static final int FOR = 17;
  public static final int ENCAPSULATE = 47;
  public static final int CHAINSIGN = 38;
  public static final int RPAREN = 11;
  public static final int IS = 23;
  public static final int LT = 41;
  public static final int COMMA = 16;
  public static final int CLASS = 31;
  public static final int ON = 28;
  public static final int BEHAVES = 29;
  public static final int MULTIPLY = 4;
  public static final int ASSIGN = 39;
  public static final int IF = 18;
  public static final int LE = 43;
  public static final int OF = 35;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int EQUAL = 9;
  public static final int error = 1;
  public static final int LIKE = 30;
  public static final int TRY = 25;
  public static final int NUMBER = 49;
  public static final int MOD = 7;
  public static final int SWITCH = 20;
  public static final int ARROW = 46;
  public static final int FOREACH = 24;
  public static final int COLON = 15;
  public static final int LBRACE = 12;
  public static final int ELSE = 19;
  public static final int WHILE = 22;
  public static final int BASED = 27;
  public static final int INSTANCE = 36;
  public static final int RBRACE = 13;
  public static final int NE = 44;
  public static final int SUM = 2;
  public static final int STRING = 50;
  public static final int EXEC = 45;
  public static final int DIVISION = 5;
  public static final int BEHAVIOUR = 32;
  public static final int GT = 40;
  public static final int CATCH = 26;
  public static final int IDENTIFIER = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUM",
  "SUBTRACT",
  "MULTIPLY",
  "DIVISION",
  "POWER",
  "MOD",
  "UMINUS",
  "EQUAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COLON",
  "COMMA",
  "FOR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "WHILE",
  "IS",
  "FOREACH",
  "TRY",
  "CATCH",
  "BASED",
  "ON",
  "BEHAVES",
  "LIKE",
  "CLASS",
  "BEHAVIOUR",
  "FUNCTION",
  "IDENTIFIER",
  "OF",
  "INSTANCE",
  "EMPTY",
  "CHAINSIGN",
  "ASSIGN",
  "GT",
  "LT",
  "GE",
  "LE",
  "NE",
  "EXEC",
  "ARROW",
  "ENCAPSULATE",
  "RETURN",
  "NUMBER",
  "STRING"
  };
}

