
package tra.models;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SATISFIED = 64;
  public static final int AS = 70;
  public static final int IDENTIFIER = 94;
  public static final int TIMES = 67;
  public static final int NAMED = 57;
  public static final int DIVISION = 11;
  public static final int GT = 47;
  public static final int ARROW = 53;
  public static final int BASED = 35;
  public static final int CHAINSIGN = 45;
  public static final int GE = 49;
  public static final int SEMI = 22;
  public static final int WORD = 4;
  public static final int UNTIL = 82;
  public static final int CAUGHT = 81;
  public static final int MEANS = 6;
  public static final int LIKE = 38;
  public static final int ARGS = 87;
  public static final int PROPS = 75;
  public static final int CATCH = 34;
  public static final int COMMA = 24;
  public static final int SUM = 8;
  public static final int RBRACE = 21;
  public static final int DEFINE = 56;
  public static final int RPAREN = 19;
  public static final int LT = 48;
  public static final int REMEMBER = 74;
  public static final int LBRACE = 20;
  public static final int ACTION = 77;
  public static final int LPAREN = 18;
  public static final int LOOP = 66;
  public static final int PROP = 91;
  public static final int NOT = 71;
  public static final int ARE = 63;
  public static final int FALSE = 62;
  public static final int LE = 50;
  public static final int OBJECT = 76;
  public static final int INSTANCE = 43;
  public static final int ERROR = 80;
  public static final int THEN = 65;
  public static final int PARAMS = 59;
  public static final int BEHAVIOUR = 40;
  public static final int EMPTY = 44;
  public static final int MOD = 13;
  public static final int CLASS = 39;
  public static final int MULTIPLY = 10;
  public static final int NUMBER = 95;
  public static final int TAB = 83;
  public static final int TRUE = 61;
  public static final int EXEC = 52;
  public static final int WHILE = 30;
  public static final int EQUAL = 17;
  public static final int EACH = 72;
  public static final int ASSIGN = 46;
  public static final int SWITCH = 28;
  public static final int DO = 79;
  public static final int FOR = 25;
  public static final int RETURN = 55;
  public static final int ELSE = 27;
  public static final int TRY = 33;
  public static final int POWER = 12;
  public static final int EOF = 0;
  public static final int ITEM = 86;
  public static final int CONDITIONS = 60;
  public static final int FUNCTION = 41;
  public static final int CAREFULLY = 78;
  public static final int IS = 31;
  public static final int IN = 73;
  public static final int ENDPROGRAM = 3;
  public static final int OR = 15;
  public static final int error = 1;
  public static final int START = 84;
  public static final int BEHAVES = 37;
  public static final int ON = 36;
  public static final int IF = 26;
  public static final int OF = 42;
  public static final int END = 85;
  public static final int COLON = 23;
  public static final int BY = 68;
  public static final int SUBTRACT = 9;
  public static final int FOREACH = 32;
  public static final int RBRACKET = 89;
  public static final int COMMAND = 7;
  public static final int ENCAPSULATE = 54;
  public static final int CASE = 29;
  public static final int NEW = 90;
  public static final int STRING = 96;
  public static final int STEP = 69;
  public static final int DOING = 93;
  public static final int WHICH = 5;
  public static final int AND = 14;
  public static final int VALUE = 92;
  public static final int STARTPROGRAM = 2;
  public static final int UMINUS = 16;
  public static final int LBRACKET = 88;
  public static final int WITH = 58;
  public static final int NE = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STARTPROGRAM",
  "ENDPROGRAM",
  "WORD",
  "WHICH",
  "MEANS",
  "COMMAND",
  "SUM",
  "SUBTRACT",
  "MULTIPLY",
  "DIVISION",
  "POWER",
  "MOD",
  "AND",
  "OR",
  "UMINUS",
  "EQUAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COLON",
  "COMMA",
  "FOR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "WHILE",
  "IS",
  "FOREACH",
  "TRY",
  "CATCH",
  "BASED",
  "ON",
  "BEHAVES",
  "LIKE",
  "CLASS",
  "BEHAVIOUR",
  "FUNCTION",
  "OF",
  "INSTANCE",
  "EMPTY",
  "CHAINSIGN",
  "ASSIGN",
  "GT",
  "LT",
  "GE",
  "LE",
  "NE",
  "EXEC",
  "ARROW",
  "ENCAPSULATE",
  "RETURN",
  "DEFINE",
  "NAMED",
  "WITH",
  "PARAMS",
  "CONDITIONS",
  "TRUE",
  "FALSE",
  "ARE",
  "SATISFIED",
  "THEN",
  "LOOP",
  "TIMES",
  "BY",
  "STEP",
  "AS",
  "NOT",
  "EACH",
  "IN",
  "REMEMBER",
  "PROPS",
  "OBJECT",
  "ACTION",
  "CAREFULLY",
  "DO",
  "ERROR",
  "CAUGHT",
  "UNTIL",
  "TAB",
  "START",
  "END",
  "ITEM",
  "ARGS",
  "LBRACKET",
  "RBRACKET",
  "NEW",
  "PROP",
  "VALUE",
  "DOING",
  "IDENTIFIER",
  "NUMBER",
  "STRING"
  };
}

